#!/bin/bash
echo "compiling..."
docker run --rm -it -v $PWD:/app -w /app durosoft/crystal-alpine:latest crystal build src/conduit.cr -o ./bin/conduit --release --static --no-debug --define production
echo "done."
