#!/bin/bash
CONDUIT_OS="unknown"
if [[ $OSTYPE == "linux-gnu" ]]; then
  CONDUIT_OS="linux"
elif [[ $OSTYPE == "linux-musl" ]]; then
  CONDUIT_OS="alpine"
elif [[ $OSTYPE == "darwin"* ]]; then
  CONDUIT_OS="macos"
fi
echo "platform: $CONDUIT_OS"
rm -rf bin/* || exit 1
ORIG=`pwd` || exit 1
echo "checking prerequisites..."
git --version || exit 1
node --version || exit 1
npm --version || exit 1
echo ""
echo "installing pkg (if not already installed)..."
pkg --version || npm install -g pkg || exit
echo ""
mkdir -p /tmp/conduit-mini-generator || exit 1
rm -rf /tmp/conduit-mini-generator/* || exit 1
cd /tmp/conduit-mini-generator || exit 1
echo "generating binaries for uglifyjs..."
git clone git@github.com:mishoo/UglifyJS2.git || exit 1
cd UglifyJS2 || exit 1
git checkout `git describe --tags` || exit 1
npm install || exit 1
pkg -t node10-$CONDUIT_OS . || exit 1
mv uglify-js $ORIG/bin/uglify-js || exit 1
cd .. || exit 1
rm -rf uglify-js || exit 1
echo ""
echo "generating binaries for clean-css-cli..."
git clone git@github.com:jakubpawlowicz/clean-css-cli.git || exit 1
cd clean-css-cli || exit 1
git checkout `git describe --tags` || exit 1
npm install || exit 1
pkg -t node10-$CONDUIT_OS . || exit 1
mv clean-css-cli $ORIG/bin/clean-css || exit 1
cd .. || exit 1
rm -rf clean-css-cli || exit 1
echo ""
echo "generating binaries for html-minifier..."
git clone git@github.com:kangax/html-minifier.git || exit 1
cd html-minifier || exit 1
git checkout `git describe --tags` || exit 1
npm install || exit 1
pkg -t node10-$CONDUIT_OS . || exit 1
mv html-minifier $ORIG/bin/html-minifier || exit 1
cd .. || exit 1
rm -rf html-minifier || exit 1
cd $ORIG || exit 1
cd bin || exit 1
echo ""
echo "verifying that packages work..."
./clean-css --version || exit 1
./html-minifier --version || exit 1
./uglify-js --version || exit 1
echo ""
echo "compressing binaries..."
mkdir -p packages
mv ./clean-css packages/clean-css || exit 1
mv ./html-minifier packages/html-minifier || exit 1
mv ./uglify-js packages/uglify-js || exit 1
tar -czvf packages.tar.gz packages || exit 1
echo ""
ls -lh packages.tar.gz
rm -rf packages || exit 1
mkdir -p packages || exit 1
mv packages.tar.gz packages/packages.tar.gz || exit 1
echo ""
echo "done."
echo ""
