#!/bin/bash
ORIG=`pwd` || exit 1
rm linux-packages.tar.gz -f
rm macos-packages.tar.gz -f
echo "checking prerequisites..."
git --version || exit 1
node --version || exit 1
npm --version || exit 1
echo ""
echo "installing pkg (if not already installed)..."
pkg --version || npm install -g pkg || exit
echo ""
mkdir -p /tmp/conduit-mini-generator || exit 1
rm -rf /tmp/conduit-mini-generator/* || exit 1
cd /tmp/conduit-mini-generator || exit 1
echo "generating binaries for uglifyjs..."
git clone git@github.com:mishoo/UglifyJS2.git || exit 1
cd UglifyJS2 || exit 1
git checkout `git describe --tags` || exit 1
npm install || exit 1
pkg -t node10-linux . || exit 1
mv uglify-js $ORIG/bin/uglify-js-linux || exit 1
pkg -t node10-macos . || exit 1
mv uglify-js $ORIG/bin/uglify-js-macos || exit 1
cd .. || exit 1
rm uglify-js -rf || exit 1
echo ""
echo "generating binaries for clean-css-cli..."
git clone git@github.com:jakubpawlowicz/clean-css-cli.git || exit 1
cd clean-css-cli || exit 1
git checkout `git describe --tags` || exit 1
npm install || exit 1
pkg -t node10-linux . || exit 1
mv clean-css-cli $ORIG/bin/clean-css-linux || exit 1
pkg -t node10-macos . || exit 1
mv clean-css-cli $ORIG/bin/clean-css-macos || exit 1
cd .. || exit 1
rm clean-css-cli -rf || exit 1
echo ""
echo "generating binaries for html-minifier..."
git clone git@github.com:kangax/html-minifier.git || exit 1
cd html-minifier || exit 1
git checkout `git describe --tags` || exit 1
npm install || exit 1
pkg -t node10-linux . || exit 1
mv html-minifier $ORIG/bin/html-minifier-linux || exit 1
pkg -t node10-macos . || exit 1
mv html-minifier $ORIG/bin/html-minifier-macos || exit 1
cd .. || exit 1
rm html-minifier -rf || exit 1
cd $ORIG || exit 1
cd bin || exit 1
echo ""
echo "verifying that linux packages work..."
./clean-css-linux --version || exit 1
./html-minifier-linux --version || exit 1
./uglify-js-linux --version || exit 1
echo ""
echo "compressing platform-specific binaries..."
mkdir -p linux-packages || exit 1
mkdir -p macos-packages || exit 1
rm linux-packages/* -rf || exit 1
rm macos-packages/* -rf || exit 1
mv *-linux linux-packages/ || exit 1
mv *-macos macos-packages/ || exit 1
rm *.tar.gz
tar -zcvf linux-packages.tar.gz linux-packages || exit 1
tar -zcvf macos-packages.tar.gz macos-packages || exit 1
echo ""
ls -lh linux-packages.tar.gz 
ls -lh macos-packages.tar.gz
rm linux-packages macos-packages -rf || exit 1
mkdir -p linux-packages || exit 1
mkdir -p macos-packages || exit 1
mv linux-packages.tar.gz linux-packages/packages.tar.gz || exit 1
mv macos-packages.tar.gz macos-packages/packages.tar.gz || exit 1
echo ""
echo "done."
echo ""
